name: Codex Agent Updater

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  codex-auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.G_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OpenAI Python SDK
        run: pip install openai

      - name: Run AGENT.md as prompt via OpenAI API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 <<EOF
import openai
import os
with open('AGENT.md') as f:
    prompt = f.read()
openai.api_key = os.getenv('OPENAI_API_KEY')
response = openai.ChatCompletion.create(
    model='gpt-4o',
    messages=[{'role': 'system', 'content': prompt}],
    max_tokens=2048,
    temperature=0.3
)
print(response.choices[0].message.content)
EOF

      - name: Commit and push changes
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          git config user.name "codex-bot"
          git config user.email "codex-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${G_TOKEN}@github.com/${{ github.repository }}.git
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "OpenAI Agent: Automated update"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi
